### ISSUE TITLE
No issue!

### ISSUE THREAD

**Issue by robsontenorio** [slava-vishnyakov/laravel-migrator#4]
Hi,

Great job! This is not a issue, it is a invitation ;)

I have noticed there is another package similar to this. I was thinking about if you are interested in join us, to build only one package!

It is called Laravel Smart: https://github.com/deiucanta/laravel-smart

Twiter contacts @deiucanta @robsontenorio

**Comment by deiucanta** [comment]
@slava-vishnyakov I want to strengthen @robsontenorio's invitation!

I launched Laravel Smart a just couple days ago and @robsontenorio reached out immediately to offer his help. This made me realize how different is to work on an open-source project along with someone else. Now I think how awesome will be if there will be 3 of us working on the same thing...

We like what you did with Laravel Migrator and we think that by joining our efforts we can make a really successful project. What do you think?

**Comment by slava-vishnyakov** [comment]
Hi guys! Thank you for the invitation! 

I like the idea, but unfortunately I don't really have time to help :)
